name: Sync and Backup

on:
  schedule:
    - cron: '0 * * * *' # runs hourly
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: node scripts/sync-to-notion.js
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Export Backups
        run: node scripts/export-backups.js
